package Mobile.Untity;
// Generated Sep 10, 2020 6:49:23 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private int imagesId;
     private ProductDetail productDetail;
     private String imagesLink;
     private Boolean imagesStatus;
     private Set banners = new HashSet(0);

    public Images() {
    }

	
    public Images(int imagesId) {
        this.imagesId = imagesId;
    }
    public Images(int imagesId, ProductDetail productDetail, String imagesLink, Boolean imagesStatus, Set banners) {
       this.imagesId = imagesId;
       this.productDetail = productDetail;
       this.imagesLink = imagesLink;
       this.imagesStatus = imagesStatus;
       this.banners = banners;
    }
   
    public int getImagesId() {
        return this.imagesId;
    }
    
    public void setImagesId(int imagesId) {
        this.imagesId = imagesId;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getImagesLink() {
        return this.imagesLink;
    }
    
    public void setImagesLink(String imagesLink) {
        this.imagesLink = imagesLink;
    }
    public Boolean getImagesStatus() {
        return this.imagesStatus;
    }
    
    public void setImagesStatus(Boolean imagesStatus) {
        this.imagesStatus = imagesStatus;
    }
    public Set getBanners() {
        return this.banners;
    }
    
    public void setBanners(Set banners) {
        this.banners = banners;
    }




}


