package Mobile.Untity;
// Generated Sep 10, 2020 6:49:23 AM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private String orderDetailId;
     private OrderPro orderPro;
     private ProductDetail productDetail;
     private Integer quantity;
     private Integer amount;
     private Boolean detailStatus;

    public OrderDetail() {
    }

	
    public OrderDetail(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public OrderDetail(String orderDetailId, OrderPro orderPro, ProductDetail productDetail, Integer quantity, Integer amount, Boolean detailStatus) {
       this.orderDetailId = orderDetailId;
       this.orderPro = orderPro;
       this.productDetail = productDetail;
       this.quantity = quantity;
       this.amount = amount;
       this.detailStatus = detailStatus;
    }
   
    public String getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public OrderPro getOrderPro() {
        return this.orderPro;
    }
    
    public void setOrderPro(OrderPro orderPro) {
        this.orderPro = orderPro;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Boolean getDetailStatus() {
        return this.detailStatus;
    }
    
    public void setDetailStatus(Boolean detailStatus) {
        this.detailStatus = detailStatus;
    }




}


