package Mobile.Untity;
// Generated Sep 10, 2020 6:49:23 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int productId;
     private Category category;
     private String productName;
     private String title;
     private String descriptions;
     private Boolean productStatus;
     private Set productDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(int productId) {
        this.productId = productId;
    }
    public Product(int productId, Category category, String productName, String title, String descriptions, Boolean productStatus, Set productDetails) {
       this.productId = productId;
       this.category = category;
       this.productName = productName;
       this.title = title;
       this.descriptions = descriptions;
       this.productStatus = productStatus;
       this.productDetails = productDetails;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Boolean getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(Boolean productStatus) {
        this.productStatus = productStatus;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }




}


