package Mobile.Untity;
// Generated Sep 10, 2020 6:49:23 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ShipType generated by hbm2java
 */
public class ShipType  implements java.io.Serializable {


     private int shipId;
     private String shipName;
     private Double fees;
     private Boolean shipStatus;
     private Set orderPros = new HashSet(0);

    public ShipType() {
    }

	
    public ShipType(int shipId) {
        this.shipId = shipId;
    }
    public ShipType(int shipId, String shipName, Double fees, Boolean shipStatus, Set orderPros) {
       this.shipId = shipId;
       this.shipName = shipName;
       this.fees = fees;
       this.shipStatus = shipStatus;
       this.orderPros = orderPros;
    }
   
    public int getShipId() {
        return this.shipId;
    }
    
    public void setShipId(int shipId) {
        this.shipId = shipId;
    }
    public String getShipName() {
        return this.shipName;
    }
    
    public void setShipName(String shipName) {
        this.shipName = shipName;
    }
    public Double getFees() {
        return this.fees;
    }
    
    public void setFees(Double fees) {
        this.fees = fees;
    }
    public Boolean getShipStatus() {
        return this.shipStatus;
    }
    
    public void setShipStatus(Boolean shipStatus) {
        this.shipStatus = shipStatus;
    }
    public Set getOrderPros() {
        return this.orderPros;
    }
    
    public void setOrderPros(Set orderPros) {
        this.orderPros = orderPros;
    }




}


