package Mobile.Untity;
// Generated Sep 10, 2020 6:49:23 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String passUser;
     private Boolean sexAdmin;
     private String mail;
     private String phone;
     private String addresss;
     private Boolean userStatus;
     private Set orderPros = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId) {
        this.userId = userId;
    }
    public Users(int userId, String userName, String passUser, Boolean sexAdmin, String mail, String phone, String addresss, Boolean userStatus, Set orderPros) {
       this.userId = userId;
       this.userName = userName;
       this.passUser = passUser;
       this.sexAdmin = sexAdmin;
       this.mail = mail;
       this.phone = phone;
       this.addresss = addresss;
       this.userStatus = userStatus;
       this.orderPros = orderPros;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassUser() {
        return this.passUser;
    }
    
    public void setPassUser(String passUser) {
        this.passUser = passUser;
    }
    public Boolean getSexAdmin() {
        return this.sexAdmin;
    }
    
    public void setSexAdmin(Boolean sexAdmin) {
        this.sexAdmin = sexAdmin;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddresss() {
        return this.addresss;
    }
    
    public void setAddresss(String addresss) {
        this.addresss = addresss;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }
    public Set getOrderPros() {
        return this.orderPros;
    }
    
    public void setOrderPros(Set orderPros) {
        this.orderPros = orderPros;
    }




}


